### ISSUE TITLE
ipyleaflet example always says that latitude upper bound is 180

### ISSUE THREAD

**Issue by wch** [posit-dev/py-shinywidgets#44]
The ipyleaflet example always says `The current latitude is [xx, 180.0]`. [App link](https://pyshiny.netlify.app/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAF21QWULgA9D8wBjAewguaTADMAnBmAAgGcAFgEsI2XsJioGnQrwBUAHQhceEnENHjJ02bwYBXQqiMB9AO7CAJgHM4hPL05wbw-hU4Xrdh07hQ6QmEANzhTZygrZR0ZOWEcABt-diS5KH5eABllVT5BQhgEwgYGBIyYvTp+fmVlNFRTA2FeAF5eJqwoO1MUpqsACmVeYfbhDCsQwYgRmdGMURNCU34E6zhOQbAALxKYRXxefYBZNF4dtSTQhP3HYKgEgzgWgBZHGFEWgEY3qEovgAYAJR4IazYYdQzGMwUaibGBoUwAI0MECsNTAwNBYPc2CSLSq-CmYLBE34qASUGwLX2KSoN14ACsDO5hOxsKZGMw4MxqfRuR56fdhDYIKZhBQYPxeXR+et6TY0LyAEzOPZgLGzTHTEZamaQxZeWz2OFofZawG1CDKKxwdgCdahDYLIyOfUu+3VYRMQGIS0zADEvAAkhBxcIhVs4LwoKjeKTyZTeOZBNzeIQUx7+F7pu4oLIMv1PhbtcN4ahWlkMCdUP0ZVzOC1+gBWJWOADMADYgY5zjAXsWZs5XO51oafCbUPSy8WNYGAOop6bpqMrNacXh0QQxuz8RwGVBWKAUNMZssAcgyvejhEInGEiKMUf6SoHIwAAhFAiE4BgAKLsdg4ECDUbTtUx+h9DUZjLDArzaZ1CFg3YIL9EZ50XM5dlEGw42EZxAgScQmBPKMyz3A8jyjZcBFWG1OAvXg7geJ8lWjWM21fYYP38L9Qj-ACgMIEDbV4cDIJLWYOn3Q8KGWWj1k2Xt6SYx4Wk-IJQnCfwBjIw5tl2M0ZwkwNf0dbAgngEjeHPDJkQMVEMk3bc4HImSqIzN05HgaouifDiNTfTyAucVF1gwGEhIk0DrIROyHIg30JJmREK3U78tMifpdP2OK0TNKCRgpOQ2mARFgH+ABdcqKscMrKuAT4KoqgrhgSYiSrKxrqtqhqqsa5qkpGZxCAMThpnYfYABUMzoUaQrkIrxQMG0JAyEAioAXzYqxeDaiBXBGla3F4damA2-ZLTqdAKwAQXQfp6kaYRHH4B11mLMANrwcBoHgNhnAARyaVV+X4cLqFoYhSDYCLaE5FgaGQeJcWSVJPoqoA)

Screenshot:
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/86978/174405905-7e47b7ac-319e-4abd-b813-e17fbe98cc54.png">

When the app starts, the console also prints this message (visible in the screenshot):

```
IndexError: tuple index out of range
```

**Comment by RolandASc** [comment]
@wch ,
maybe you could update the last part of the first `ipyleaflet` example in the **README** to do something like this:

```python
    # Everytime the map's bounds change, update the output message (3)
    @output
    @render.text
    def map_bounds():
        b = reactive_read(map, "bounds")

        def scale_b(x):
            x_new = abs(x) % 360 * x / abs(x)
            if x_new > 180:
                x_new -= 360
            elif x_new < -180:
                x_new += 360
            return x_new

        if b:
            lat = [b[0][0], b[1][0]]
            lon = [b[0][1], b[1][1]]
            lon = [scale_b(x) for x in lon]
            return f"The current latitude is {lat} and longitude is {lon}"
```

The `if b:` is to prevent the error upon initialization (`IndexError: tuple index out of range`).

I swapped (fixed) the elements for lat / lon so that `lat` contains the bottom and the top bound, and added a function to rescale the `lon` bounds back to the usual space between -180 and +180, even when you horizontally drag across the map multiple times.  
Also `map = L.Map(center=(52, 0), zoom=4)` would appear to make more sense with `0` instead of `360` then.
